#!/bin/bash

set -e

v="1.0.9.6 Beta"

function usage {
	cat << USAGE

Auto IPA Builder v$v

Usage: build 'option'

Help: 
      build 'deblist' - Shows the list of required Debs and their names
      build 'ipalist' - Shows the list of required IPAs and their names
      build 'optionslist' - Shows the list of options for the build command

USAGE
	exit 1
}

[[ $# = 0 ]] && usage

commands=(deblist ipalist optionslist cercube4 cercube4pp)
[[ ! " ${commands[@]} " =~ " $1 " ]] && usage

function deblist {
	echo "Debs must be in a folder called Tweaks on your Desktop"
	echo "Debs:
      None.deb
      None.deb"
}

function ipalist {
	echo "IPAs must be in a folder called Tweaks on your Desktop"
	echo "IPAs:
      YouTube.ipa
      YouTube.ipa"
}

function optionslist {
	echo "Options:
      cercube4 - Builds Cercube 4
      cercube4pp - Builds Cercube 4++"
}

function cercube4 {
	echo "Building Cercube 4"
	cd ~/Desktop/Tweaks
	mkdir -p Build
	cd Build
	echo "Downloading Tweak"
	curl -O "https://files.hollr2099.net/tweaksold/cercube4.zip"
	echo "Extracting IPA"
	unzip ../YouTube.ipa -d YouTube > /dev/null
	echo "Extracting Tweak"
	unzip cercube4.zip -d Cercube4 > /dev/null
	echo "Moving Tweak"
	cd Cercube4
	rm -r -f __MACOSX
	cp -r * ../YouTube/Payload/YouTube.app
	cd ../
	echo "Injecting Tweak"
	optool install -c load -p "@executable_path/Cercube.dylib" -t "YouTube/Payload/YouTube.app/YouTube" > /dev/null
	cd YouTube; rm -r -f __MACOSX
	echo "Packaging IPA"
	zip -r -X ../"Cercube 4 For YouTube.ipa" * > /dev/null
	cd ../
	echo "Removing Folders"
	rm -r -f cercube4.zip Cercube4 YouTube
	echo "Done Cercube 4"
}

function cercube4pp {
	echo "Building Cercube 4++"
	cd ~/Desktop/Tweaks
	mkdir -p Build
	cd Build
	echo "Downloading Tweak"
	curl -O "https://files.hollr2099.net/tweaksold/cercube4.zip"
	curl -O "https://files.hollr2099.net/tweaksold/cercube4pp.zip"
	echo "Extracting IPA"
	unzip ../YouTube.ipa -d YouTube > /dev/null
	echo "Extracting Tweak"
	unzip cercube4.zip -d Cercube4 > /dev/null
	unzip cercube4pp.zip -d Cercube4PP > /dev/null
	echo "Moving Tweak"
	cd Cercube4
	rm -r -f __MACOSX
	cp -r * ../YouTube/Payload/YouTube.app
	cd ../
	cd Cercube4PP
	rm -r -f __MACOSX
	cp -r * ../YouTube/Payload/YouTube.app
	cd ../
	echo "Injecting Tweak"
	optool install -c load -p "@executable_path/Cercube.dylib" -t "YouTube/Payload/YouTube.app/YouTube" > /dev/null
	optool install -c load -p "@executable_path/CercubeCrack.dylib" -t "YouTube/Payload/YouTube.app/YouTube" > /dev/null
	cd YouTube; rm -r -f __MACOSX
	echo "Packaging IPA"
	zip -r -X ../"Cercube 4 For YouTube++.ipa" * > /dev/null
	cd ../
	echo "Removing Folders"
	rm -r -f cercube4.zip cercube4pp.zip Cercube4 Cercube4PP YouTube
	echo "Done Cercube 4++"
}

"$1" "${@:2}"