#!/bin/bash

set -e

v="1.0.9.6 Beta"

function usage {
	cat << USAGE

Auto IPA Builder v$v

Usage: build 'option'

Help: 
      build 'deblist' - Shows the list of required Debs and their names
      build 'ipalist' - Shows the list of required IPAs and their names
      build 'optionslist' - Shows the list of options for the build command

USAGE
	exit 1
}

[[ $# = 0 ]] && usage

commands=(deblist ipalist optionslist cercube4 cercube4pp plexpp spotifypp)
[[ ! " ${commands[@]} " =~ " $1 " ]] && usage

function deblist {
	echo "Debs must be in a folder called Tweaks on your Desktop"
	echo "Debs:
      Currently not avaiable"
}

function ipalist {
	echo "IPAs must be in a folder called Tweaks on your Desktop"
	echo "IPAs:
      Plex.ipa
      Spotify.ipa
      YouTube.ipa"
}

function optionslist {
	echo "Options:
      cercube4 - Builds Cercube 4
      cercube4pp - Builds Cercube 4++
      spotifypp - Builds Spotify++"
}

function cercube4 {
	echo "Building Cercube 4"
	cd ~/Desktop/Tweaks
	mkdir -p Build
	cd Build
	echo "Extracting IPA"
	unzip ../YouTube.ipa -d YouTube > /dev/null
	cd "YouTube/Payload/YouTube.app";
	echo "Downloading Tweak"
	curl -O "https://raw.githubusercontent.com/SarahH12099/Auto-IPA-Builder-Tweaks/master/cercube4.zip"
	echo "Extracting Tweak"
	unzip cercube4.zip > /dev/null
	rm -r -f cercube4.zip
	echo "Injecting Tweak"
	optool install -c load -p "@executable_path/Cercube.dylib" -t "YouTube" > /dev/null
	echo "Packaging IPA"
	cd ../../
	zip -r -X ../"Cercube 4 For YouTube.ipa" * > /dev/null
	cd ../; rm -r -f YouTube
	echo "Done Cercube 4"
}

function cercube4pp {
	echo "Building Cercube 4++"
	cd ~/Desktop/Tweaks
	mkdir -p Build
	cd Build
	echo "Extracting IPA"
	unzip ../YouTube.ipa -d YouTube > /dev/null
	cd "YouTube/Payload/YouTube.app";
	echo "Downloading Tweak"
	curl -O "https://raw.githubusercontent.com/SarahH12099/Auto-IPA-Builder-Tweaks/master/cercube4.zip"
	curl -O "https://raw.githubusercontent.com/SarahH12099/Auto-IPA-Builder-Tweaks/master/cercube4pp.zip"
	echo "Extracting Tweak"
	unzip cercube4.zip > /dev/null
	unzip cercube4pp.zip > /dev/null
	rm -r -f cercube4.zip
	rm -r -f cercube4pp.zip
	echo "Injecting Tweak"
	optool install -c load -p "@executable_path/Cercube.dylib" -t "YouTube" > /dev/null
	optool install -c load -p "@executable_path/CercubeCrack.dylib" -t "YouTube" > /dev/null
	echo "Packaging IPA"
	cd ../../
	zip -r -X ../"Cercube 4 For YouTube++.ipa" * > /dev/null
	cd ../; rm -r -f YouTube
	echo "Done Cercube 4++"
}

function plexpp {
	echo "Building Plex++"
	cd ~/Desktop/Tweaks
	mkdir -p Build
	cd Build
	echo "Extracting IPA"
	unzip ../Plex.ipa -d Plex > /dev/null
	cd "Plex/Payload/PlexMobile.app";
	echo "Downloading Tweak"
	curl -O "https://raw.githubusercontent.com/SarahH12099/Auto-IPA-Builder-Tweaks/master/plexpp.zip"
	echo "Extracting Tweak"
	unzip plexpp.zip > /dev/null
	rm -r -f plexpp.zip
	echo "Injecting Tweak"
	optool install -c load -p "@executable_path/PlexCrack.dylib" -t "PlexMobile" > /dev/null
	echo "Packaging IPA"
	cd ../../
	zip -r -X ../"Plex++.ipa" * > /dev/null
	cd ../; rm -r -f Plex
	echo "Done Plex++"
}

function spotifypp {
	echo "Building Spotify++"
	cd ~/Desktop/Tweaks
	mkdir -p Build
	cd Build
	echo "Extracting IPA"
	unzip ../Spotify.ipa -d Spotify > /dev/null
	cd "Spotify/Payload/Spotify.app";
	echo "Downloading Tweak"
	curl -O "https://raw.githubusercontent.com/SarahH12099/Auto-IPA-Builder-Tweaks/master/spotifypp.zip"
	echo "Extracting Tweak"
	unzip spotifypp.zip > /dev/null
	rm -r -f spotifypp.zip
	echo "Injecting Tweak"
	install_name_tool -change /usr/lib/libSystem.B.dylib @executable_path/Sys.dylib Spotify > /dev/null
	echo "Packaging IPA"
	cd ../../
	zip -r -X ../"Spotify++.ipa" * > /dev/null
	cd ../; rm -r -f Spotify
	echo "Done Spotify++"
}

"$1" "${@:2}"